---
- hosts: bootstrap
  gather_facts: true
  roles:
    - role: build_config
    - role: post_install/create_kubeconfig
    - role: post_install/install_coredns
    - role: post_install/install_calico