---
- hosts: all
  gather_facts: true
  roles:
    - role: build_config
    - role: pre_install/update_etc_hosts

# - hosts: all
#   gather_facts: true
#   roles:
#     - role: pre_install/set_host_name

