- name: Extract cni plugins
  become: true
  ansible.builtin.unarchive:
    src: "{{ node_packages_dir }}/cni-plugins-linux-amd64-{{ cni_plugins_version }}.tgz"
    dest: /opt/cni/bin
    remote_src: true

- name: worker_pod_cidr
  set_fact:
    worker_pod_cidr: "{{ workers | selectattr('host_name','eq', ansible_hostname) | map(attribute='pod_cidr') | first }}"

- name: Create 10-bridge.conf
  become: true
  template:
    src: 10-bridge.conf.j2
    dest: /etc/cni/net.d/10-bridge.conf

- name: Create 99-loopback.conf
  become: true
  template:
    src: 99-loopback.conf.j2
    dest: /etc/cni/net.d/99-loopback.conf