- name: Debug | ansible_ssh_host
  debug: 
    msg: "{{ inventory_hostname }}"

- name: Create service file for etcd 
  become: true
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service